### ISSUE TITLE
Tests for valid encoding

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [inikulin/cookie-compat#4]
Hi, I have built a lot of tests covering all the allowed and not allowed cookie values according to RFC 6265, which represents all characters allowed in all major browsers when the spec was created (and which seems to stand until today).

I am not sure what is the goal of this repo, but it might be useful somehow: https://github.com/js-cookie/js-cookie/blob/72d05c27ebfb99aa8b6ae8f1b46210e223e815b9/test/encoding.js

It runs in all relevant browsers including IE6: https://saucelabs.com/u/js-cookie

**Comment by inikulin** [comment]
Hi, thank you for the contribution! I guess it's better be issued to the upstream [IETF test suite](https://github.com/abarth/http-state/tree/master/tests). This particular project is focused on test runner and results analysis.

**Comment by FagnerMartinsBrack** [comment]
Oh ok, nevermind then :)
